import { type DefaultLayoutTranslations } from '@vidstack/react';

const SPANISH: DefaultLayoutTranslations = {
  'Caption Styles': '',
  'Captions look like this': '',
  'Closed-Captions Off': '',
  'Closed-Captions On': '',
  'Display Background': '',
  'Enter Fullscreen': '',
  'Enter PiP': '',
  'Exit Fullscreen': '',
  'Exit PiP': '',
  'Google Cast': '',
  'Keyboard Animations': '',
  'Seek Backward': '',
  'Seek Forward': '',
  'Skip To Live': '',
  'Text Background': '',
  Accessibility: '',
  AirPlay: '',
  Announcements: '',
  Audio: '',
  Auto: '',
  Boost: '',
  Captions: '',
  Chapters: '',
  Color: '',
  Connected: '',
  Connecting: '',
  Continue: '',
  Default: '',
  Disabled: '',
  Disconnected: '',
  Download: '',
  Family: '',
  Font: '',
  Fullscreen: '',
  LIVE: '',
  Loop: '',
  Mute: '',
  Normal: '',
  Off: '',
  Opacity: '',
  Pause: '',
  PiP: '',
  Play: '',
  Playback: '',
  Quality: '',
  Replay: '',
  Reset: '',
  Seek: '',
  Settings: '',
  Shadow: '',
  Size: '',
  Speed: '',
  Text: '',
  Track: '',
  Unmute: '',
  Volume: '',
};
