import { type DefaultLayoutTranslations } from '@vidstack/react';

const SPANISH: DefaultLayoutTranslations = {
  Audio: '',
  Auto: '',
  Captions: '',
  Chapters: '',
  Continue: '',
  'Closed-Captions Off': '',
  'Closed-Captions On': '',
  Default: '',
  'Enter Fullscreen': '',
  'Enter PiP': '',
  'Exit Fullscreen': '',
  'Exit PiP': '',
  LIVE: '',
  Mute: '',
  Normal: '',
  Off: '',
  Pause: '',
  Play: '',
  Quality: '',
  Replay: '',
  Reset: '',
  Seek: '',
  Settings: '',
  'Seek Backward': '',
  'Seek Forward': '',
  'Skip To Live': '',
  Speed: '',
  Unmute: '',
  // Remote Playback
  AirPlay: '',
  'Google Cast': '',
  Connected: '',
  Connecting: '',
  Disconnected: '',
  // Font Menu
  'Background Color': '',
  'Background Opacity': '',
  'Display Background Color': '',
  'Display Background Opacity': '',
  'Font Family': '',
  'Font Size': '',
  'Font Styles': '',
  'Text Color': '',
  'Text Opacity': '',
  'Text Shadow': '',
  // Colors
  Black: '',
  Cyan: '',
  Green: '',
  Magenta: '',
  Red: '',
  White: '',
  Yellow: '',
};
