import { type PlyrLayoutTranslations } from '@vidstack/react';

const SPANISH: PlyrLayoutTranslations = {
  Ad: '',
  All: '',
  AirPlay: '',
  Audio: '',
  Auto: '',
  Buffered: '',
  Captions: '',
  'Current time': '',
  Default: '',
  'Disable captions': '',
  Disabled: '',
  Download: '',
  Duration: '',
  'Enable captions': '',
  Enabled: '',
  End: '',
  'Enter Fullscreen': '',
  'Exit Fullscreen': '',
  Forward: '',
  'Go back to previous menu': '',
  LIVE: '',
  Loop: '',
  Mute: '',
  Normal: '',
  Pause: '',
  'Enter PiP': '',
  'Exit PiP': '',
  Play: '',
  Played: '',
  Quality: '',
  Reset: '',
  Restart: '',
  Rewind: '',
  Seek: '',
  Settings: '',
  Speed: '',
  Start: '',
  Unmute: '',
  Volume: '',
};
